---
title: "2.VisualizingResults_2016.12.02.plot"
author: "Ciera Martinez"
date: "December 2, 2016"
output: html_document
---

```{r}
library(ggplot2)
```

Wildtype
```{r}
allGO <- read.csv("data_output/outputFromVisualizingResults_2017Sept05_clean.csv") 
dim(allGO)
head(allGO)

allGO <- allGO[,-1]

colnames(allGO)[10] <- "direction"
colnames(allGO)[12] <- "analysis"

# subset only significantly enriched
allGO <- subset(allGO, over_represented_pvalue < .05)
head(allGO)

summary(allGO$analysis)

tf2 <- c("tf2ambr_tf2aother", "tf2bmbr_tf2bother", "tf2cmbr_tf2cother")
wt <- c("wtambr_wtaother", "wtbmbr_wtbother", "wtcmbr_wtcother")

tf2_all <- subset(allGO, subset = analysis %in% tf2)
#write.csv(tf2_all, file = "./data_output/revigo_tf2_long_05Sept2017.csv")

wt_all <- subset(allGO, subset = analysis %in% wt)
#write.csv(wt_all, file = "./data_output/revigo_WT_long_05Sept2017.csv")

## For output into REVIGO
revigo_wt <- as.data.frame(unique(factor(wt_all$category)))
#write.csv(revigo_wt, file = "./data_output/revigo_WT_05Sept2017.csv")

revigo_tf2 <- as.data.frame(unique(factor(tf2_all$category)))
#write.csv(revigo_tf2, file = "./data_output/revigo_tf2_05Sept2017.csv")
```

Went to REVIGO and entered in GO terms. 

```{r}
wt_BP <- read.csv("../../requisiteData/WT_REVIGO_BP.csv", skip = 4)
wt_MF <- read.csv("../../requisiteData/WT_REVIGO_MF.csv", skip = 4)
wt_CC <- read.csv("../../requisiteData/WT_REVIGO_CC.csv", skip = 4)

revigo_output <- rbind(wt_CC, wt_MF, wt_BP)

# merge with original Data
dim(revigo_output)
head(revigo_output)
colnames(revigo_output)
dim(wt_all)
colnames(wt_all)
head(wt_all)
colnames(wt_all)[1] <- "term_ID"

wt_sig_revigo <- merge(wt_all, revigo_output, by = "term_ID", all.x = TRUE)

dim(wt_sig_revigo)
head(wt_sig_revigo,50)

## Make significanve categories.
wt_sig_revigo$significance <- "NS" #makes a column where every row says "NS"
wt_sig_revigo$significance[wt_sig_revigo$over_represented_pvalue <= 0.05] <- "0.05" #labels everything less than or = to 0.05
wt_sig_revigo$significance[wt_sig_revigo$over_represented_pvalue <= 0.01] <- "0.01" #ect
wt_sig_revigo$significance[wt_sig_revigo$over_represented_pvalue <= 0.001] <- "0.001"
wt_sig_revigo$significance[wt_sig_revigo$over_represented_pvalue <= 0.0001] <- "0.0001"

head(wt_sig_revigo)

#remove NA
wt_sig_revigo <- wt_sig_revigo[complete.cases(wt_sig_revigo),]

#remove ALL
wt_sig_revigo <- subset(wt_sig_revigo, direction != "all")
str(wt_sig_revigo)
colnames(wt_sig_revigo)

```

## Visualization

```{r}

## Maybe split into more groups?
head(wt_sig_revigo)
length(levels(factor(wt_sig_revigo$term))) #335 terms
length(levels(wt_sig_revigo$representative)) # only 59


# The naming scheme is for analysis.  Since they are going to subsetted, I think I will chance the name.

wt_sig_revigo$analysis <- gsub("wtcmbr_wtcother", "base", wt_sig_revigo$analysis)
wt_sig_revigo$analysis <- gsub("wtambr_wtaother", "top", wt_sig_revigo$analysis)
wt_sig_revigo$analysis <- gsub("wtbmbr_wtbother", "mid", wt_sig_revigo$analysis)

## Make new column to seperate up and down regulated 
colnames(wt_sig_revigo)
wt_sig_revigo$region <- apply(wt_sig_revigo[ , c(10,12) ] , 1 , paste , collapse = "-" )

levels(factor((wt_sig_revigo$region)))

head(wt_sig_revigo)

ggplot(wt_sig_revigo, aes(region, term, color = direction)) +
    scale_color_manual(values = c( "lightskyblue", "grey")) +
    theme_bw() +
    theme(axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank()) +
    geom_point(size = 3, 
               alpha = .7, 
               position = position_jitterdodge()) +
    facet_grid(.~analysis, 
               scales = "free") 

head(wt_sig_revigo)

wt_sig_revigo$significance <- as.numeric(wt_sig_revigo$significance)
wt_sig_revigo$over_represented_pvalue <- as.numeric(wt_sig_revigo$over_represented_pvalue)

## For Ordering terms in Visualization
wt_sig_revigo <- with(wt_sig_revigo, wt_sig_revigo[order(region, direction),])
wt_sig_revigo$term <- factor(wt_sig_revigo$term, levels = unique(as.character(wt_sig_revigo$term)) )

ggplot(wt_sig_revigo, aes(region, term, color = direction, size = significance)) +
  scale_color_manual(values = c( "lightskyblue", "black")) +
  theme_bw(base_size = 18) +
  scale_size("over_represented_pval") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank()) +
  geom_point(alpha = .7) +
  facet_grid(.~analysis, 
             scales = "free") 

## Write out terms for subsetting
# terms <- as.data.frame(levels(factor(wt_sig_revigo$term)))
# write.csv(terms, "../../requisiteData/allGOterms.csv")
```

There is just wayyyyy too many GO categories, but I think we can just limit the ones we want to highlight. So I manually choose the categories that were meaningful and wanted to highlight. I exported and read in the categories I wanted to highlight for the main figure.

```{r}

term_subset <- read.csv("../../requisiteData/allGOterms_chosenSubset.csv")
term_subset <- term_subset[,-1]
term_subset$chosen <- as.factor(term_subset$chosen)

term_subset <- subset(term_subset, chosen == "1")

terms_sub <- as.vector(term_subset$levels.factor.wt_sig_revigo.term..)

wt_sig_revigo_sub <- wt_sig_revigo[wt_sig_revigo$term %in% terms_sub,]
head(wt_sig_revigo_sub)

#Change the long terms slightly
wt_sig_revigo_sub$term <- gsub("transcription factor", "TF", wt_sig_revigo_sub$term)
wt_sig_revigo_sub$term <- gsub("transmembrane", "", wt_sig_revigo_sub$term)
wt_sig_revigo_sub$term <- gsub("core promoter proximal region sequence-specific", "", wt_sig_revigo_sub$term)
wt_sig_revigo_sub$term <- gsub("\\(apurinic or apyrimidinic site\\)", "", wt_sig_revigo_sub$term)

#check
levels(factor(wt_sig_revigo_sub$term))
wt_sig_revigo_sub$term <- factor(wt_sig_revigo_sub$term) 

## Make new column to seperate up and down regulated 
colnames(wt_sig_revigo_sub)
wt_sig_revigo$region <- apply(wt_sig_revigo[ , c(8,9) ] , 1 , paste , collapse = "-" )

levels(factor((wt_sig_revigo$region)))
head(wt_sig_revigo)

ggplot(wt_sig_revigo, aes(analysis, representative, size = significance, color = direction)) +
  scale_color_manual(values  = c( "lightblue", "black")) +
  geom_point(size = 3, alpha = .6, position = position_jitterdodge())

#ordering
## For Ordering terms in Visualization
wt_sig_revigo_sub <- with(wt_sig_revigo_sub, wt_sig_revigo_sub[order(region, direction),])
wt_sig_revigo_sub$term <- factor(wt_sig_revigo_sub$term, levels = unique(as.character(wt_sig_revigo_sub$term)) )

# re- label headings.

head(wt_sig_revigo_sub)
wt_sig_revigo_sub$direction <- gsub("down", "margin", wt_sig_revigo_sub$direction)
wt_sig_revigo_sub$direction <- gsub("up", "rachis", wt_sig_revigo_sub$direction)

### Why can't I get size of significance to be correct
wt_sig_revigo_sub$significance <- as.numeric(wt_sig_revigo_sub$significance)
wt_sig_revigo_sub$over_represented_pvalue <- as.numeric(wt_sig_revigo_sub$over_represented_pvalue)
plot(wt_sig_revigo_sub$over_represented_pvalue)

ggplot(wt_sig_revigo_sub, aes(region, term, color = direction, size = over_represented_pvalue)) +
  scale_color_manual(values = c( "grey", "lightskyblue")) +
  theme_bw()  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 20),
        legend.position = "none") +
  geom_point() +
  #scale_size(range = c(3, 8)) +
  scale_radius(range = c(2, 6)) +
  facet_grid(.~analysis, 
             scales = "free") 

#other way around looks ugly
ggplot(wt_sig_revigo_sub, aes(term, region, color = direction, size = significance)) +
  scale_color_manual(values = c( "lightskyblue", "grey")) +
  theme_bw()  +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_point() +
  scale_size(range = c(2, 5)) +
  facet_grid(analysis~., 
             scales = "free") +
  theme(legend.position = "none")

```

