---
title: "2.VisualizingResults_2016.12.02.plot"
author: "Ciera Martinez"
date: "December 2, 2016"
output: html_document
---

```{r}
library(ggplot2)
```

tf-2
```{r}
allGO <- read.csv("data_output/outputFromVisualizingResults_2017Sept05_clean.csv") 
dim(allGO)
head(allGO)

allGO <- allGO[,-1]

colnames(allGO)[10] <- "direction"
colnames(allGO)[12] <- "analysis"

# subset only significantly enriched
allGO <- subset(allGO, over_represented_pvalue < .05)
head(allGO)

summary(allGO$analysis)

tf2 <- c("tf2ambr_tf2aother", "tf2bmbr_tf2bother", "tf2cmbr_tf2cother")

tf2_all <- subset(allGO, subset = analysis %in% tf2)
#write.csv(tf2_all, file = "./data_output/revigo_tf2_long_05Sept2017.csv")

revigo_tf2 <- as.data.frame(unique(factor(tf2_all$category)))
write.csv(revigo_tf2, file = "./data_output/revigo_tf2_05Sept2017.csv")
```

Went to REVIGO and entered in GO terms. 

```{r}
tf2_BP <- read.csv("../../requisiteData/tf2_REVIGO_treemap_BP.csv", skip = 4)
tf2_CC <- read.csv("../../requisiteData/tf2_REVIGO_treemap_CC.csv", skip = 4)
tf2_MF <- read.csv("../../requisiteData/tf2_REVIGO_treemap_MF.csv", skip = 4)

revigo_output <- rbind(tf2_CC, tf2_MF, tf2_BP)

# merge with original Data
dim(revigo_output)
head(revigo_output)
colnames(revigo_output)
dim(tf2_all)
colnames(tf2_all)
head(tf2_all)
colnames(tf2_all)[1] <- "term_ID"

tf2_sig_revigo <- merge(tf2_all, revigo_output, by = "term_ID", all.x = TRUE)

dim(tf2_sig_revigo)
head(tf2_sig_revigo,50)

## Make significanve categories.
tf2_sig_revigo$significance <- "NS" #makes a column where every row says "NS"
tf2_sig_revigo$significance[tf2_sig_revigo$over_represented_pvalue <= 0.05] <- "0.05" #labels everything less than or = to 0.05
tf2_sig_revigo$significance[tf2_sig_revigo$over_represented_pvalue <= 0.01] <- "0.01" #ect
tf2_sig_revigo$significance[tf2_sig_revigo$over_represented_pvalue <= 0.001] <- "0.001"
tf2_sig_revigo$significance[tf2_sig_revigo$over_represented_pvalue <= 0.0001] <- "0.0001"

head(tf2_sig_revigo)

#remove NA
tf2_sig_revigo <- tf2_sig_revigo[complete.cases(tf2_sig_revigo),]

#remove ALL
tf2_sig_revigo <- subset(tf2_sig_revigo, direction != "all")
str(tf2_sig_revigo)
colnames(tf2_sig_revigo)
```

## Visualization

```{r}

## Maybe split into more groups?
head(tf2_sig_revigo)
length(levels(factor(tf2_sig_revigo$term))) #173 terms
length(levels(tf2_sig_revigo$representative)) # only 40


# The naming scheme is for analysis.  Since they are going to subsetted, I think I will chance the name.

tf2_sig_revigo$analysis <- gsub("tf2cmbr_tf2cother", "base", tf2_sig_revigo$analysis)
tf2_sig_revigo$analysis <- gsub("tf2ambr_tf2aother", "top", tf2_sig_revigo$analysis)
tf2_sig_revigo$analysis <- gsub("tf2bmbr_tf2bother", "mid", tf2_sig_revigo$analysis)

## Make new column to seperate up and down regulated 
colnames(tf2_sig_revigo)
tf2_sig_revigo$region <- apply(tf2_sig_revigo[ , c(10,12) ] , 1 , paste , collapse = "-" )

levels(factor((tf2_sig_revigo$region)))

head(tf2_sig_revigo)

ggplot(tf2_sig_revigo, aes(region, term, color = direction)) +
    scale_color_manual(values = c( "lightskyblue", "grey")) +
    theme_bw() +
    theme(axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank()) +
    geom_point(size = 3, 
               alpha = .7, 
               position = position_jitterdodge()) +
    facet_grid(.~analysis, 
               scales = "free") 

head(tf2_sig_revigo)

tf2_sig_revigo$significance <- as.numeric(tf2_sig_revigo$significance)
tf2_sig_revigo$over_represented_pvalue <- as.numeric(tf2_sig_revigo$over_represented_pvalue)

## For Ordering terms in Visualization
tf2_sig_revigo <- with(tf2_sig_revigo, tf2_sig_revigo[order(region, direction),])
tf2_sig_revigo$term <- factor(tf2_sig_revigo$term, levels = unique(as.character(tf2_sig_revigo$term)) )

ggplot(tf2_sig_revigo, aes(region, term, color = direction, size = significance)) +
  scale_color_manual(values = c( "lightskyblue", "black")) +
  theme_bw(base_size = 18) +
  scale_size("over_represented_pval") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank()) +
  geom_point(alpha = .7) +
  facet_grid(.~analysis, 
             scales = "free") 

## Write out terms for subsetting
terms <- as.data.frame(levels(factor(tf2_sig_revigo$term)))
write.csv(terms, "../../requisiteData/tf2_allGOterms.csv")
```

There is just wayyyyy too many GO categories, but I think we can just limit the ones we want to highlight. So I manually choose the categories that were meaningful and wanted to highlight. I exported and read in the categories I wanted to highlight for the main figure.

```{r}

term_subset <- read.csv("../../requisiteData/tf2_allGOterms_chosenSubset.csv")
term_subset <- term_subset[,-1]
term_subset$chosen <- as.factor(term_subset$chosen)

term_subset <- subset(term_subset, chosen == "1")

terms_sub <- as.vector(term_subset$levels.factor.tf2_sig_revigo.term..)

tf2_sig_revigo_sub <- tf2_sig_revigo[tf2_sig_revigo$term %in% terms_sub,]
head(tf2_sig_revigo_sub)
dim(tf2_sig_revigo_sub)

#Change the long terms slight for visualization
tf2_sig_revigo_sub$term <- gsub("transcription factor", "TF", tf2_sig_revigo_sub$term)
tf2_sig_revigo_sub$term <- gsub("transmembrane", "", tf2_sig_revigo_sub$term)
tf2_sig_revigo_sub$term <- gsub("regulatory region", "", tf2_sig_revigo_sub$term)
tf2_sig_revigo_sub$term <- gsub(" V-type ATPase, V0 domain", "", tf2_sig_revigo_sub$term)
tf2_sig_revigo_sub$term <- gsub(", nonsense-mediated decay", "", tf2_sig_revigo_sub$term)

#check
levels(factor(tf2_sig_revigo_sub$term))
wt_sig_revigo_sub$term <- factor(wt_sig_revigo_sub$term) 

## Make new column to seperate up and down regulated 
colnames(tf2_sig_revigo_sub)
tf2_sig_revigo$region <- apply(tf2_sig_revigo[ , c(8,9) ] , 1 , paste , collapse = "-" )

levels(factor((tf2_sig_revigo$region)))
head(tf2_sig_revigo)

ggplot(tf2_sig_revigo, aes(analysis, representative, size = significance, color = direction)) +
  scale_color_manual(values  = c( "lightblue", "black")) +
  geom_point(size = 3, alpha = .6, position = position_jitterdodge())

#ordering
## For Ordering terms in Visualization
tf2_sig_revigo_sub <- with(tf2_sig_revigo_sub, tf2_sig_revigo_sub[order(region, direction),])
tf2_sig_revigo_sub$term <- factor(tf2_sig_revigo_sub$term, levels = unique(as.character(tf2_sig_revigo_sub$term)) )

# re- label headings.

head(tf2_sig_revigo_sub)
tf2_sig_revigo_sub$direction <- gsub("down", "margin", tf2_sig_revigo_sub$direction)
tf2_sig_revigo_sub$direction <- gsub("up", "rachis", tf2_sig_revigo_sub$direction)

### Why can't I get size of significance to be correct
tf2_sig_revigo_sub$significance <- as.numeric(tf2_sig_revigo_sub$significance)
tf2_sig_revigo_sub$over_represented_pvalue <- as.numeric(tf2_sig_revigo_sub$over_represented_pvalue)
plot(tf2_sig_revigo_sub$over_represented_pvalue)

ggplot(tf2_sig_revigo_sub, aes(region, term, color = direction, size = over_represented_pvalue)) +
  scale_color_manual(values = c( "grey", "lightskyblue")) +
  theme_bw()  +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        text = element_text(size = 25),
        legend.position = "none") +
  geom_point() +
  #scale_size(range = c(3, 8)) +
  scale_radius(range = c(2, 6)) +
  facet_grid(.~analysis, 
             scales = "free") 
```

